name: Docker Image # nome do processo

on:
  push:
    branches:
      - main # roda quando faz um push na branch "main"

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        # baixa o código do repositório

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        # configura o buildx

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # faz login no docker hub com o usuário e senha

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sauter-ellie:latest
     
